version: '2'
services:
 postgres:
  build: ./postgres
  image: ricardojob/banco
  container_name: banco
  ports: 
    - "5433:5432"
 web:
  build: .
  image: ricardojob/app
  container_name: app
  ports: 
    - "8082:8080" 
  links: 
    - "postgres:host-banco"   